name: CI

on:
  pull_request:
    branches: [ master ]
  merge_group:
    types: [ checks_requested ]
  push:
    branches: [ master ]
  workflow_dispatch: { }

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}

      - name: Build & Test
        uses: ./.github/actions/gradle-check
