name: Release

on:
  workflow_dispatch: { }

permissions:
  contents: write # Required to create tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with: # We have to fetch full history because we need old tags
          fetch-depth: 0

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: false

      - id: version
        name: Determine Version
        uses: ./.github/actions/determine-release-version

      - name: Build javadoc
        uses: ./.github/actions/gradle-check
        with:
          tasks: javadoc
        env:
          MINESTOM_VERSION: ${{ steps.version.outputs.version }}

      - name: Publish to Maven Central
        if: github.repository == 'Minestom/Minestom'
        run: ./gradlew publishAggregationToCentralPortal
        env:
          MINESTOM_VERSION: ${{ steps.version.outputs.version }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}

      - name: Deploy javadoc to its assigned branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: javadoc
          FOLDER: build/docs/javadoc
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAR_GLOBS_FILE: ".github/javadoc-publish-clear"

      - name: Create Tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
